services:
    backend:
        image: node:24-bookworm
        container_name: watermelondb-backend
        volumes:
            - ./backend:/watermelondb-api
        working_dir: /watermelondb-api
        command: npm run start:debug
        ports:
            - 3000:3000
            - 9229:9229
        env_file: ./backend/.env.${NODE_ENV}
        environment: # setting environment variables for server config, settings here will override those in the .env file
            - NODE_ENV=${NODE_ENV}
            - TZ=${TZ}
        depends_on:
            - redis
            - mysql
        networks:
            custom_network:
                aliases:
                    - watermelondb.network

    redis:
        image: redis:8-alpine
        container_name: watermelondb-redis
        environment:
            - TZ=${TZ}
        ports:
            - 6379:6379
        networks:
            custom_network:
                aliases:
                    - watermelondb.network

    mysql:
        image: mysql:9.4
        container_name: watermelondb-mysql
        env_file:
            - ./backend/.env.${NODE_ENV}
        environment:
            - TZ=${TZ}
        ports:
            - 3306:3306
        volumes:
            - watermelondb-mysql:/var/lib/mysql
        networks:
            custom_network:
                aliases:
                    - watermelondb.network

    phpmyadmin:
        image: phpmyadmin
        container_name: watermelondb-phpmyadmin
        # restart: always
        ports:
            - 8080:80
        environment:
            - PMA_ARBITRARY=1
            - TZ=${TZ}
        networks:
            custom_network:
                aliases:
                    - watermelondb.network

volumes:
    watermelondb-mysql:

networks:
    custom_network:
        driver: bridge
