services:
  redis:
    image: redis:7.4.1-alpine3.20
    container_name: redis
    environment:
      - TZ=${TZ}
    ports:
      - 6379:6379
    networks:
      custom_network:
        aliases:
          - eisenboard.nestjs.rb-dev.net

  mysql:
    image: mysql:8.4
    container_name: mysql
    env_file:
      - ./api/.env.${NODE_ENV}
    environment:
      - TZ=${TZ}
    ports:
      - 3306:3306
    volumes:
      - eisenboard-mysql:/var/lib/mysql
    networks:
      custom_network:
        aliases:
          - eisenboard.nestjs.rb-dev.net

  mail:
    image: mailhog/mailhog
    container_name: mail
    ports:
      # - 1025:1025
      - 8025:8025
    environment:
      - TZ=${TZ}
    networks:
      custom_network:
        aliases:
          - eisenboard.nestjs.rb-dev.net

volumes:
  eisenboard-mysql:

networks:
  custom_network:
    driver: bridge
