services:
  frontend:
    hostname: app.eisenboard.de
    image: registry.renebedbur.de/rbedbur/eisenboard.app/eisenboard-ui:latest
    container_name: eisenboard-ui
    restart: unless-stopped
    environment:
      - NODE_ENV=${NODE_ENV}
      - TZ=${TZ}
    depends_on:
      - backend
    networks:
      - eisenboard.app-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.eisenboard-ui.tls.certresolver=lets-encrypt
      - traefik.http.routers.eisenboard-ui.rule=Host(`app.eisenboard.de`)
      - traefik.http.routers.eisenboard-ui.tls=true
      - traefik.http.routers.eisenboard-ui.service=eisenboard-ui
      - traefik.docker.network=eisenboard.app-network
      - traefik.http.services.eisenboard-ui.loadbalancer.server.port=3080

  backend:
    image: registry.renebedbur.de/rbedbur/eisenboard.app/eisenboard-api:latest
    container_name: eisenboard-api
    restart: unless-stopped
    working_dir: /app
    env_file: ./api/.env.${NODE_ENV}
    environment: # setting environment variables for server config, settings here will override those in the .env file
      - NODE_ENV=${NODE_ENV}
      - TZ=${TZ}
    depends_on:
      - redis
      - mysql
    networks:
      - eisenboard.app-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.eisenboard-api.tls.certresolver=lets-encrypt
      - traefik.http.routers.eisenboard-api.rule=Host(`app.eisenboard.de`) && PathPrefix(`/api`)
      - traefik.http.routers.eisenboard-api.tls=true
      - traefik.http.routers.eisenboard-api.service=eisenboard-api
      - traefik.docker.network=eisenboard.app-network
      - traefik.http.services.eisenboard-api.loadbalancer.server.port=3000

  redis:
    image: redis:7.4.1-alpine3.20
    container_name: eisenboard-redis
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    networks:
      - eisenboard.app-network

  mysql:
    image: mysql:8.4.0-oraclelinux9
    container_name: eisenboard-mysql
    restart: unless-stopped
    env_file:
      - ./api/.env.${NODE_ENV}
    environment:
      - TZ=${TZ}
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - eisenboard.app-network

volumes:
  mysql:

networks:
  eisenboard.app-network:
    external: true
